### ISSUE TITLE
Api response 

### ISSUE THREAD

**Issue by deeppatidar** [Newput-Time-tracker/backend#23]
Please change the api response format 
current format : -----
{"response":{"data":[{"msg":null}],"success":false,"rcode":"505","error":"Email id already registered"
}}

require format :------
{"data":[{"msg":null}],"success":false,"rcode":"505","error":"Email id already registered"
}

**Comment by rahulkulmi** [comment]
Api response is now proper format.
Ex : require format :------
{"data":[{"msg":null}],"success":false,"rcode":"505","error":"Email id already registered"
}
